filmu_failas = "data\\filmai.pickle"
seansu_failas = "data\\seansai.pickle"
vartotoju_failas = "data\\vartotojai.pickle"
ivertinimu_failas = "data\\ivertinimai.pickle"
pardavimu_failas = "data\\pardavimai.pickle"